export TAU_OPTIONS="-optVerbose -optRevert"
export TEST_CC_MPI=mpicc
export TEST_CXX_MPI=mpicxx
export TEST_FTN_MPI=mpif90
export TEST_CC=icc
export TEST_CXX=icpc
export TEST_FTN=ifort
export TEST_RUN_CMD=mpirun
export TEST_RUN_PROCFLAG="-np"
export TEST_RUN_PROCARG="4"
export TEST_RUN="$TEST_RUN_CMD $TEST_RUN_PROCFLAG $TEST_RUN_PROCARG"
