#!/bin/bash -e
. ./setup.sh
set -x
cd ./build
echo CTEST_FULL_OUTPUT
export CUDA_MANAGED_FORCE_DEVICE_ALLOC=1
export CUDA_LAUNCH_BLOCKING=1
export OMP_NUM_THREADS=4
${TEST_RUN}  ./iallreduce 
#./Zoltan 1024
