PROGRAM CALLF2
  IMPLICIT NONE

  INTERFACE
     SUBROUTINE F2( N, M )
       INTEGER, INTENT( IN )  :: N
       INTEGER, INTENT( OUT ) :: M
     END SUBROUTINE F2
  END INTERFACE
  
  INTEGER :: NB, RES
  NB = 8
  CALL F2( NB, RES )

END PROGRAM
